# Generated by Django 3.1.4 on 2020-12-20 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DairyManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milkcollection',
            old_name='total_price_per_day',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='milkcollection',
            name='your_message',
        ),
    ]
