# Generated by Django 3.1.4 on 2020-12-21 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DairyManagement', '0002_auto_20201220_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_field',
        ),
        migrations.AlterField(
            model_name='madesale',
            name='juror',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DairyManagement.userprofile'),
        ),
        migrations.AlterField(
            model_name='milkcollection',
            name='juror',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DairyManagement.userprofile'),
        ),
    ]
