# Generated by Django 3.1.4 on 2020-12-21 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DairyManagement', '0003_auto_20201221_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='madesale',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile3', to='DairyManagement.userprofile'),
        ),
        migrations.AddField(
            model_name='milkcollection',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile2', to='DairyManagement.userprofile'),
        ),
        migrations.AlterField(
            model_name='madesale',
            name='juror',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='milkcollection',
            name='juror',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
